export const day1 = [
    {
        sl: 1,
        timing: "9:30 A.M. - 10:30 A.M.",
        name: "Inauguration (B Block Seminar Hall)",
        round: "-",
    },
    {
        sl: 2,
        timing: "10:30 A.M. - 12:00 P.M.",
        name: "Omegatrix (C Block Auditorium 7th Floor)",
        round: "Prelims",
    },
    {
        sl: 3,
        timing: "10:30 A.M. - 1:30 P.M.",
        name: "FIFA (C Block Room no 201 Lab 8)",
        round: "Prelims",
    },
    {
        sl: 4,
        timing: "10:30 A.M. - 1:30 P.M.",
        name: "Passion with Reels (B block Seminar Hall)",
        round: "Final",
    },
    {
        sl: 5,
        timing: "12:15 P.M. - 1:30 P.M.",
        name: "PES (C Block Auditorium 7th Floor)",
        round: "Prelims",
    },
    {
        sl: 6,
        timing: "12:00 P.M. - 1:30 P.M.",
        name: "Code-Bee (C Block Lab 101, 102, 104, 105, 601, 602)",
        round: "Qualifier Round 1",
    },
    {
        sl: 7,
        timing: "10:30 A.M. - 1:30 P.M.",
        name: "Ro-Terrance (B Block 204)",
        round: "Qualifier Round",
    },
    {
        sl: 7,
        timing: "",
        name: "Ro-Navigator (B Block 304)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 7,
        timing: "",
        name: "Ro-Soccer (B-Block 205)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 7,
        timing: "",
        name: "Aqua Race (B- Block 202)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 7,
        timing: "",
        name: "Khet (B Block 404)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 8,
        timing: "10:30 A.M. - 5:30 P.M.",
        name: "Ro-Combat (C Block)",
        round: "Bot Testing & Playoff",
    },
    {
        sl: 9,
        timing: "1:30 P.M. - 2:30 P.M.",
        name: "LUNCH BREAK",
        round: "-",
    },
    {
        sl: 10,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "PES (C Block Auditorium 7th Floor)",
        round: "Prelims",
    },
    {
        sl: 11,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "Code-Bee (C Block Lab 101, 102, 104, 105, 601, 602)",
        round: "Qualifier Round 2",
    },
    {
        sl: 12,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "Ro-Terrance (B Block 204)",
        round: "Qualifier Round",
    },
    {
        sl: 12,
        timing: "",
        name: "Ro-Navigator (B Block 304)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Ro-Soccer (B Block 205)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Aqua Race (B Block 202)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Khet (B Block 404)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 13,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "FIFA (C Block Room no 201 Lab 8)",
        round: "Prelims",
    },
];

export const day2 = [
    {
        sl: 1,
        timing: "10:00 A.M. - 1:00 P.M.",
        name: "Technomania (B Block Lab 602 & 603)",
        round: "Final",
    },
    {
        sl: 2,
        timing: "10:00 A.M. - 12:00 P.M.",
        name: "Tech Hunt (C Block Auditorium 7th Floor)",
        round: "Prelims",
    },
    {
        sl: 3,
        timing: "10:30 A.M. - 1:30 P.M.",
        name: "FIFA (C Block Room no 201 Lab 8)",
        round: "Final",
    },
    {
        sl: 4,
        timing: "10:30 A.M. - 1:30 P.M.",
        name: "Ro-Terrance (B Block 204)",
        round: "Final",
    },
    {
        sl: 4,
        timing: "",
        name: "Ro-Navigator (B Block 304)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 4,
        timing: "",
        name: "Ro-Soccer (B Block 205)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 4,
        timing: "",
        name: "Aqua Race (B Block 202)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 4,
        timing: "",
        name: "Khet (B Block 404)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 5,
        timing: "10:00 A.M. - 1:30 P.M",
        name: "Hackstorm (C block Lab 101, 102, 104)",
        round: "Prelims",
    },
    {
        sl: 6,
        timing: "12:00 P.M. - 01:30 P.M.",
        name: "Omegatrix (C Block Auditorium 7th Floor)",
        round: "Final",
    },
    {
        sl: 7,
        timing: "1:30 P.M. - 2:30 P.M.",
        name: "LUNCH BREAK",
        round: "-",
    },
    {
        sl: 8,
        timing: "2:30 P.M. - 5:00 P.M",
        name: "Hackstorm (B block Seminar Hall)",
        round: "Final",
    },
    {
        sl: 9,
        timing: "2:30 P.M. - 5:00 P.M.",
        name: "Code Bee ( C block Lab 101, 102, 104, 105, 601, 602)",
        round: "Final",
    },
    {
        sl: 10,
        timing: "2:30 P.M. - 5:00 P.M.",
        name: "PES (C Block Auditorium 7th Floor)",
        round: "Final",
    },
    {
        sl: 11,
        timing: "2:30 A.M. - 5:30 P.M.",
        name: "Tech Hunt",
        round: "Final",
    },
    {
        sl: 12,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "Ro-Terrance (B Block 204)",
        round: "Final",
    },
    {
        sl: 12,
        timing: "",
        name: "Ro-Navigator (B Block 304)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Ro-Soccer (B Block 205)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Aqua Race (B Block 202)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 12,
        timing: "",
        name: "Khet (B Block 404)",
        round: "",
        noBorderTop: true,
    },
    {
        sl: 13,
        timing: "2:30 P.M. - 5:30 P.M.",
        name: "Shutter Fusion (C Block Student Activity Room)",
        round: "Final",
    },
];

export const day3 = [
    {
        sl: 1,
        timing: "01:00 P.M. - 02:00 P.M.",
        name: "Prize Distribution Ceremony",
        round: "-",
    },
    {
        sl: 2,
        timing: "02:00 P.M. - 02:15 P.M.",
        name: "Vote of Thanks",
        round: "-",
    },
    {
        sl: 3,
        timing: "02:15 P.M. - 03:30 P.M.",
        name: "Cultural Programme",
        round: "-",
    },
];